name: Tests

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  build:

    runs-on: ubuntu-latest
                
    steps:      
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer update --prefer-dist --no-interaction --no-suggest

    - name: Run tests
      run: vendor/bin/phpunit --verbose
