name: Tests

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      mysql:        
        image: mysql:5.7
        env:
          MYSQL_DATABASE: avolutions
          MYSQL_USER: avolutions
          MYSQL_PASSWORD: avolutions
        ports:
          - 33306:3306
            
    steps:      
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer update --prefer-dist --no-interaction --no-suggest

    - name: Run tests
      run: vendor/bin/phpunit --verbose
      env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          DB_USERNAME: root
