# AVOLUTIONS
#
# Just another open source PHP framework.
#
# @copyright    Copyright (c) 2019 - 2021 AVOLUTIONS
# @license      MIT License (https://avolutions.org/license)
# @link         https://avolutions.org

name: Tests

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      mysql:
          image: mysql:5.7
          env:
              MYSQL_ROOT_PASSWORD: avolutions
              MYSQL_DATABASE: avolutions
              MYSQL_USER: avolutions
              MYSQL_PASSWORD: avolutions
          ports:
            - 3306
          options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP with PECL extension
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: mysql

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer update --prefer-dist --no-interaction --no-suggest

    - name: Run tests
      run: vendor/bin/phpunit --verbose
      env:
        DB_PORT: ${{ job.services.mysql.ports[3306] }}
